version: "3"

services:
  master:
    build:
      context: ./docker/locust
    environment:
      - SWBENCH_DATA_DIR=/mnt/data/${SWBENCH_NAME}
    ports:
      - "8089:8089"
    volumes:
      - ./:/mnt/locust
      - ~/.swbench:/mnt/data
    working_dir: /mnt/locust
