---
php_version: 8.0
php_extensions:
  - common
  - dev
  - cli
  - fpm
  - curl
  - mysql
  - gd
  - sqlite3
  - mbstring
  - xml
  - intl
  - zip
  - memcache
  - memcached
  - imagick
  - soap
php_packages: []
