---
- name: "Install Elasticsearch repository key"
  apt_key: url="https://artifacts.elastic.co/GPG-KEY-elasticsearch" state="present"

- name: "Add Elasticsearch repository"
  apt_repository: repo="deb https://artifacts.elastic.co/packages/7.x/apt stable main" state="present" update_cache="yes"

- name: "Install Elasticsearch"
  apt: name="elasticsearch" state="latest" install_recommends="yes"
  notify: "Restart Elasticsearch"

- name: "Configure Elasticsearch to be run upon boot"
  systemd: name="elasticsearch" state=started enabled=yes
  notify: "Restart Elasticsearch"
