---
- name: Install MySQL server
  apt:
    pkg: ["mysql-server-8.0", "python3-mysqldb"]
  register: mysql_installed

- name: MySQL Upgrade
  command: "mysql_upgrade"
  ignore_errors: yes
  register: mysql_upgraded
  when: mysql_installed is changed

- name: Restart MySQL after update or install
  systemd: name=mysql state=restarted
  when: mysql_installed is changed or mysql_upgraded is changed

- name: "Update mysqld.cnf"
  template:
    src: mysqld.j2
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
  notify: "Restart MySQL"

- name: update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql_root_password }} priv=*.*:ALL,GRANT
  with_items:
   - "{{ ansible_all_ipv4_addresses | ipaddr('private') | first }}"
   - 127.0.0.1
   - ::1
   - localhost

- name: copy .my.cnf file with root password credentials
  template: src=mysqlcnf.j2 dest=/root/.my.cnf owner=root mode=0600

- name: Create shopware6 database
  mysql_db:
    name: shopware6
    state: present
    collation: utf8_general_ci
    encoding: utf8
    login_host: localhost
    login_user: root
    login_password: "{{ mysql_root_password }}"
