---
- name: gather facts from all
  hosts: all
  tasks: ~

- name: web-role
  hosts: web
  tags: [web]
  roles:
    - web

- name: mysql-role
  hosts: mysql
  tags: [mysql]
  roles:
    - mysql

- name: "Redis-role"
  hosts: redis
  tags: [redis]
  roles:
    - redis

- name: "Elasticsearch"
  hosts: elastic
  tags: [elastic]
  roles:
    - elasticsearch

- name: "Shopware"
  hosts: web
  tags: [shopware]
  roles:
    - shopware
