---
- name: web-role
  hosts: web
  vars:
    php_version: 8.0
    php_extensions:
      - common
      - dev
      - cli
      - fpm
      - curl
      - mysql
      - gd
      - sqlite3
      - mbstring
      - xml
      - intl
      - zip
      - memcache
      - memcached
      - imagick
      - soap
    php_packages: []
  tasks:
    - apt: 
        pkg: ["curl", "git"]
        update_cache: yes

    - name: Add ondrej/php ppa
      apt_repository: >
          repo=ppa:ondrej/php
          state=present
          update_cache=yes

    - name: Install PHP
      apt: pkg=php{{ php_version }} state=present

    - name: Build a list of all the additional PHP packages
      set_fact:
        php_packages: "{{ php_packages }} + [ 'php{{ php_version }}-{{ item }}' ]"
      with_items: "{{ php_extensions }}"

    - name: Install PHP extensions
      apt: pkg='{{ php_packages }}' state=present
      notify: Restart PHP-FPM

    - name: Configure php.ini
      template:
        src: phpini.j2
        dest: /etc/php/{{ php_version }}/mods-available/custom.ini
      notify: Restart PHP-FPM

    - name: Update custom phpenmod module
      shell: phpenmod -v ALL custom

    - name: Setup fpm pool
      template:
        src: phpfpm.j2
        dest: /etc/php/{{ php_version }}/fpm/pool.d/www.conf

    - name: Install apache
      apt:
        pkg: ["apache2"]

#- name: Setup dummy folder for shopware
#file:
#path: /var/www/shopware6/public
#state: directory
#owner: www-data
#group: www-data

    - name: Configure Apache Vhost
      template:
        src: apache.j2
        dest: /etc/apache2/sites-enabled/000-default.conf
      notify: Restart Apache

- name: mysql-role
  hosts: mysql
  vars:
    mysql_root_password: "root"
  tasks:
    - name: Install MySQL server
      apt:
        pkg: ["mysql-server-8.0", "python3-mysqldb"]
      register: mysql_installed

    - name: MySQL Upgrade
      command: "mysql_upgrade"
      ignore_errors: yes
      register: mysql_upgraded
      when: mysql_installed is changed

    - name: Restart MySQL after update or install
      systemd: name=mysql state=restarted
      when: mysql_installed is changed or mysql_upgraded is changed

    - name: update mysql root password for all root accounts
      mysql_user: name=root host={{ item }} password={{ mysql_root_password }} priv=*.*:ALL,GRANT
      with_items:
       - "{{ ansible_hostname }}"
       - 127.0.0.1
       - ::1
       - localhost

    - name: copy .my.cnf file with root password credentials
      template: src=mysqlcnf.j2 dest=/root/.my.cnf owner=root mode=0600
        
    - name: Create shopware6 database
      mysql_db: 
        name: shopware6
        state: present
        collation: utf8_general_ci
        encoding: utf8
        login_host: localhost
        login_user: root
        login_password: "{{ mysql_root_password }}"

- name: "Redis-role"
  hosts: redis
  vars:
    redis_bind_ip: "127.0.0.1"
    redis_port: 6379
  tasks:
    - name: "Install Redis"
      apt: pkg=redis-server
      notify: Restart Redis

    - name: Redis Daemon Configuration
      template: >
        src=redis.j2
        dest=/etc/redis/redis.conf
        owner=root
        group=root
        mode=0644
      notify: Restart Redis

  handlers:
    - name: Restart PHP-FPM
      systemd: 
        name: php{{ php_version }}-fpm
        state: restarted

    - name: Restart Apache
      systemd:
        name: apache2
        state: restarted

    - name: Restart Redis
      systemd:
        name: redis-server
        state: restarted
