---
- name: Testing
  hosts: all
  vars:
    php_version: 8.0
    php_extensions:
      - common
      - dev
      - cli
      - fpm
      - curl
      - mysql
      - gd
      - sqlite3
      - mbstring
      - xml
      - intl
      - zip
      - memcache
      - memcached
      - imagick
      - soap
    php_packages: []
  tasks:
    - apt: 
        pkg: ["curl", "git"]
        update_cache: yes

    - name: Add ondrej/php ppa
      apt_repository: >
          repo=ppa:ondrej/php
          state=present
          update_cache=yes

    - name: Install PHP
      apt: pkg=php{{ php_version }} state=present

    - name: Build a list of all the additional PHP packages
      set_fact:
        php_packages: "{{ php_packages }} + [ 'php{{ php_version }}-{{ item }}' ]"
      with_items: "{{ php_extensions }}"

    - name: Install PHP extensions
      apt: pkg='{{ php_packages }}' state=present
      notify: Restart PHP-FPM

    - name: Configure php.ini
      template:
        src: phpini.j2
        dest: /etc/php/{{ php_version }}/mods-available/custom.ini
      notify: Restart PHP-FPM

    - name: Update custom phpenmod module
      shell: phpenmod -v ALL custom

  handlers:
    - name: Restart PHP-FPM
      systemd: 
        name: php{{ php_version }}-fpm
        state: restarted
